development:
  DEBUG: True
  DATABASE:
    ENGINE: django.db.backends.mysql
    NAME: django_model_mall
    USER: root
    PASSWORD: '5483201'
    HOST: localhost
    PORT: 3306

production:
  DEBUG: False
  DATABASE:
    ENGINE: django.db.backends.mysql
    NAME: django_model_mall
    USER: root
    PASSWORD: '3b4502d1e93360a8'
    HOST: 172.19.60.234
    PORT: 3306
